# Generated by Django 3.2 on 2021-10-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0003_donation_request_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donation_request_view',
            table=None,
        ),
    ]
