# Generated by Django 3.2 on 2021-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0005_alter_donation_request_view_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation_request_view',
            name='id',
        ),
        migrations.AlterField(
            model_name='donation_request_view',
            name='ngo_name',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
