# Generated by Django 3.2 on 2021-10-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0006_auto_20211023_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterModelOptions(
            name='donation_request_view',
            options={'managed': False},
        ),
    ]
