# Generated by Django 3.2 on 2021-10-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0007_auto_20211023_1939'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donation_request_view',
            table='post_request',
        ),
    ]
