# Generated by Django 3.2 on 2021-10-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0008_alter_donation_request_view_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation_request_view',
            options={},
        ),
    ]
