# Generated by Django 3.2 on 2021-10-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0009_alter_donation_request_view_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation_request_view',
            options={'managed': False},
        ),
    ]
