# Generated by Django 3.2 on 2021-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0010_alter_donation_request_view_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='verification_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
